In [1]:
import numpy as np 

In [3]:
arr = np.random.randint(5,50,100)
arr 

array([ 7, 27, 29,  8, 46, 40, 16, 30, 29, 13, 41, 33, 38, 48, 41, 16, 26,
       32, 19, 34, 19, 29, 12, 20, 25, 18, 48,  9, 20,  8, 33, 28, 18, 33,
       40, 44, 46,  8, 48, 16, 31, 16, 42,  6, 46, 43, 17, 28, 47, 30, 39,
       24, 30, 41, 44, 46, 21, 42, 19,  8, 14, 49, 37,  7, 35, 35, 25, 13,
       46, 19,  7, 16, 20, 27, 43, 15, 21, 23, 10,  5,  7, 31, 37, 16, 20,
       17, 23, 31, 24, 33, 29, 20, 33, 40, 28, 17, 49, 25, 13,  6])

In [7]:
arr.mean()  # , max() , min() , sum()  , mean()==average()

26.81

In [8]:
arr = np.random.randint(5,50,(4,3))
arr

array([[23, 37,  7],
       [10, 27, 24],
       [12,  9, 15],
       [19, 46, 13]])

In [10]:
arr.shape  

(4, 3)

In [12]:
np.transpose(arr).shape

(3, 4)

In [13]:
arr.T

array([[23, 10, 12, 19],
       [37, 27,  9, 46],
       [ 7, 24, 15, 13]])

In [15]:
arr = np.random.randint(2,12,(10,5))
arr 

array([[ 8,  8,  9, 11,  5],
       [ 7,  9,  6,  2,  8],
       [ 8, 11,  4,  5,  7],
       [ 3,  9,  9,  7,  2],
       [10,  6,  6, 10,  2],
       [ 6,  5,  4,  4,  9],
       [ 8,  8,  5,  7, 11],
       [ 3,  3,  2,  4,  8],
       [ 7,  2, 11,  6, 10],
       [11,  2,  7,  5,  7]])

In [18]:
arr.reshape(50,)

array([ 8,  8,  9, 11,  5,  7,  9,  6,  2,  8,  8, 11,  4,  5,  7,  3,  9,
        9,  7,  2, 10,  6,  6, 10,  2,  6,  5,  4,  4,  9,  8,  8,  5,  7,
       11,  3,  3,  2,  4,  8,  7,  2, 11,  6, 10, 11,  2,  7,  5,  7])

In [19]:
arr

array([[ 8,  8,  9, 11,  5],
       [ 7,  9,  6,  2,  8],
       [ 8, 11,  4,  5,  7],
       [ 3,  9,  9,  7,  2],
       [10,  6,  6, 10,  2],
       [ 6,  5,  4,  4,  9],
       [ 8,  8,  5,  7, 11],
       [ 3,  3,  2,  4,  8],
       [ 7,  2, 11,  6, 10],
       [11,  2,  7,  5,  7]])

In [25]:
arr[-10:,-5:-3]

array([[ 8,  8],
       [ 7,  9],
       [ 8, 11],
       [ 3,  9],
       [10,  6],
       [ 6,  5],
       [ 8,  8],
       [ 3,  3],
       [ 7,  2],
       [11,  2]])

In [34]:
arr = np.random.randint(2,50,(5,10,5))
arr

array([[[46, 22, 25, 14, 32],
        [26, 12, 32, 34, 19],
        [12, 43, 16,  4, 43],
        [46, 15, 41, 42, 20],
        [13, 21, 29, 20, 26],
        [19, 19, 22, 44, 34],
        [46, 21,  5, 21, 42],
        [46, 13, 22, 11, 33],
        [29, 28, 22, 11, 18],
        [21, 37, 31, 10, 18]],

       [[33, 32, 26, 10, 37],
        [33, 43, 10,  2, 26],
        [26, 14,  7,  3,  7],
        [13, 38, 46, 13, 10],
        [37, 46, 12, 47, 38],
        [35, 48, 28, 17, 25],
        [49, 49, 19, 12, 39],
        [46, 46, 43, 43,  3],
        [37, 27,  9, 17, 30],
        [16, 30, 25,  6, 42]],

       [[48,  9, 32, 21,  5],
        [27, 47, 46, 16, 30],
        [32, 34, 30, 11, 45],
        [41, 23,  5, 19, 25],
        [24, 20, 40, 40,  2],
        [25, 47, 33, 49, 44],
        [45, 37, 19, 31,  2],
        [38,  3, 20, 31, 10],
        [ 3,  3, 13, 41, 40],
        [17, 24, 26, 43,  3]],

       [[31, 44, 34,  2, 23],
        [11, 26, 38, 11, 16],
        [37,  9, 35, 22, 15],
    

In [28]:
arr.shape 
#T , R , C 

(5, 10, 5)

In [29]:
arr.ndim

3

In [35]:
arr[0]   # you will get a table 

array([[46, 22, 25, 14, 32],
       [26, 12, 32, 34, 19],
       [12, 43, 16,  4, 43],
       [46, 15, 41, 42, 20],
       [13, 21, 29, 20, 26],
       [19, 19, 22, 44, 34],
       [46, 21,  5, 21, 42],
       [46, 13, 22, 11, 33],
       [29, 28, 22, 11, 18],
       [21, 37, 31, 10, 18]])

In [36]:
print(arr[:,9:,:])

[[[21 37 31 10 18]]

 [[16 30 25  6 42]]

 [[17 24 26 43  3]]

 [[30 16 29 40 28]]

 [[ 4 26 30 10  5]]]


In [50]:
arr = np.array([7,5,9])
arr 

array([7, 5, 9])

In [38]:
arr.max()

9

In [40]:
arr.argmin()  # argmax()

1

In [45]:
arr.sort()   # 

In [52]:
arr.argsort()   #  5   7   9  

array([1, 0, 2], dtype=int64)

In [53]:
arr 

array([7, 5, 9])

In [54]:
arr = np.random.randint(2,12,(10,5))
arr 

array([[ 6,  6,  3,  5,  4],
       [ 3,  6,  7, 10, 10],
       [ 2, 10,  8, 11,  2],
       [ 3,  8,  4,  3,  5],
       [10,  6, 10,  5,  5],
       [ 3,  3,  8, 10,  6],
       [ 8,  2,  9,  9,  6],
       [ 6,  3,  5, 10,  4],
       [ 8,  5,  4,  4, 10],
       [ 7,  9,  8,  2,  8]])

In [55]:
np.unique(arr)  # 

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [59]:
arr = np.random.randint(2,250,200)
arr 

array([186, 248,  87, 115,  20,  20, 236, 227, 179, 105, 249, 127,  19,
        19, 115,  68,  74,  74, 206, 177,  31, 225,  91, 149, 200,   5,
        89,  14,  53,  62,  47,  10, 127, 197, 129, 144,  52, 120, 237,
       185, 221,  34, 185, 160,  20, 228, 158, 131, 217,  59, 205,  57,
       184,  91, 173, 171, 165, 142,  92,  45, 237,  81, 203, 195,  69,
        79,  86,  19,  70, 158, 222, 162, 161, 111,   6,  94, 175, 100,
       109, 235, 187,  55, 162, 160, 242, 132,  91,  21, 136, 125,  15,
       170,  25,  69,  45,  13,  62, 163, 101, 109,  75, 195, 249, 185,
       220,  57, 117, 134, 158, 193, 111,  85,  79,   7, 226,  82,  10,
       232,  46, 110, 117, 186,  84, 139, 237,  98,   9, 117, 152, 241,
       178, 124,  59, 215, 170, 239, 128, 163, 113, 109,  71,  22, 136,
       245,  20, 155, 106, 120, 139,  37, 126, 187,  38,  55, 115,  50,
       105, 248, 160, 217, 149, 183,  79, 138,  85,  71,  46,  16,  16,
        41,  36,  54, 153, 206, 127, 153, 168,  86, 228,  25,  2

In [63]:
np.median(arr)   # mean() 

121.5

In [64]:
arr.var()

5009.2291

In [65]:
arr.std()

70.77590762399306

In [66]:
np.sqrt(25)   

5.0

In [68]:
# numpy   

In [70]:
# pandas 
# !pip install pandas  

In [72]:
import pandas as pd 
print("imported")

imported
